In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
df=pd.read_csv('pakwheel.csv')
df

,vehicle_name,city,date_added,model,mileage,fuel,engine_capacity,auto_manual,price
0,KIA Sportage 2021 AWD,Lahore,Updated less than a minute ago,2021,"35,000 km",Petrol,2000 cc,Automatic,PKR 56 lacs
1,Toyota Prius 2020 A Premium Touring Selection,Islamabad,Updated 2 minutes ago,2020,"29,000 km",Petrol,1800 cc,Automatic,PKR 73 lacs
2,Toyota Yaris 2022 ATIV X CVT 1.5,Karachi,Updated 2 minutes ago,2022,30 km,Petrol,0.0 kWh,Automatic,PKR 37.9 lacs
3,Suzuki Alto 2022 VXR,Rawalpindi,Updated 5 minutes ago,2022,400 km,Petrol,660 cc,Manual,PKR 20.6 lacs
4,Toyota Vitz 2008 F 1.0,Rawalpindi,Updated 7 minutes ago,2008,"150,000 km",Petrol,1000 cc,Automatic,PKR 17.25 lacs
...,...,...,...,...,...,...,...,...,...
60394,Suzuki Mehran 2019 VX Euro II,Islamabad,Updated about 1 month ago,2019,"24,000 km",Petrol,800 cc,Manual,PKR 11.2 lacs
60395,Honda BR-V 2018 i-VTEC S,Mansehra,Updated about 1 month ago,2018,"65,000 km",Petrol,1500 cc,Automatic,PKR 35.25 lacs
60396,Suzuki Alto 2009,Islamabad,Updated about 1 month ago,2009,"224,000 km",Petrol,1000 cc,Manual,PKR 8 lacs
60397,Suzuki Wagon R 2022 VXL,Peshawar,Updated about 1 month ago,2022,10 km,Petrol,1000 cc,Manual,PKR 23 lacs
60398,Toyota Prius 2013 S LED Edition 1.8,Faisalabad,Updated about 1 month ago,2013,"200,000 km",Hybrid,1800 cc,Automatic,PKR 31.5 lacs

In [3]:
# new column
from datetime import date

time=[]
today=str(date.today())
year1,month1,date1=today.split('-')
day1=int('13')
month1=int(month1)
year1=int(year1)

for i in range(len(df.date_added)):
    x=df.date_added[i].lower().strip('updated ').strip('about ')
    if 'hour' in x or 'minutes' in x or 'minute' in x:
        date='{}/{}/{}'.format(day1,month1,year1) 
    elif 'days' in x or 'day' in x:
        days=int(x.strip(' days ago').strip(' day ago'))
        if day1-days<=0:
            days=30-(days-day1)
            date='{}/{}/{}'.format(days,month1-1,year1)
        else:
            date='{}/{}/{}'.format(day1-days,month1,year1)
    elif 'months' in x or 'month' in x:
        months=int(x.strip(' months ago').strip(' month ago'))
        if month1-months<=0:
            months=12-(months-month1)
            date='{}/{}/{}'.format(day1,months,year1-1)
        else:
            date='{}/{}/{}'.format(day1,month1-months,year1)
    elif 'years' in x or 'year' in x:
        years=int(x.strip('updated ').strip(' years ago').strip(' year ago'))
        date='{}/{}/{}'.format(day1,month1,year1-years)
    else:
        date='error'
    time.append(date)
    
df.insert(9,'Time_added',time)
df

,vehicle_name,city,date_added,model,mileage,fuel,engine_capacity,auto_manual,price,Time_added
0,KIA Sportage 2021 AWD,Lahore,Updated less than a minute ago,2021,"35,000 km",Petrol,2000 cc,Automatic,PKR 56 lacs,13/6/2022
1,Toyota Prius 2020 A Premium Touring Selection,Islamabad,Updated 2 minutes ago,2020,"29,000 km",Petrol,1800 cc,Automatic,PKR 73 lacs,13/6/2022
2,Toyota Yaris 2022 ATIV X CVT 1.5,Karachi,Updated 2 minutes ago,2022,30 km,Petrol,0.0 kWh,Automatic,PKR 37.9 lacs,13/6/2022
3,Suzuki Alto 2022 VXR,Rawalpindi,Updated 5 minutes ago,2022,400 km,Petrol,660 cc,Manual,PKR 20.6 lacs,13/6/2022
4,Toyota Vitz 2008 F 1.0,Rawalpindi,Updated 7 minutes ago,2008,"150,000 km",Petrol,1000 cc,Automatic,PKR 17.25 lacs,13/6/2022
...,...,...,...,...,...,...,...,...,...,...
60394,Suzuki Mehran 2019 VX Euro II,Islamabad,Updated about 1 month ago,2019,"24,000 km",Petrol,800 cc,Manual,PKR 11.2 lacs,13/5/2022
60395,Honda BR-V 2018 i-VTEC S,Mansehra,Updated about 1 month ago,2018,"65,000 km",Petrol,1500 cc,Automatic,PKR 35.25 lacs,13/5/2022
60396,Suzuki Alto 2009,Islamabad,Updated about 1 month ago,2009,"224,000 km",Petrol,1000 cc,Manual,PKR 8 lacs,13/5/2022
60397,Suzuki Wagon R 2022 VXL,Peshawar,Updated about 1 month ago,2022,10 km,Petrol,1000 cc,Manual,PKR 23 lacs,13/5/2022
60398,Toyota Prius 2013 S LED Edition 1.8,Faisalabad,Updated about 1 month ago,2013,"200,000 km",Hybrid,1800 cc,Automatic,PKR 31.5 lacs,13/5/2022

In [4]:
cost=[]
for i in range(len(df.price)):
    x=df.price[i].lower().replace(',','')
    if 'lacs' in x:
        num=float(x.strip('pkr ').strip(' lacs'))*100000
    elif 'crore' in x:
        num=float(x.strip('pkr ').strip(' crore'))*10000000
    elif x=='call':
        num='Call'
    elif 'pkr' in x:
        num=float(x.strip('pkr '))
    else:
        num='error'
    cost.append(num)
df.insert(10,'Cost',cost)
df

,vehicle_name,city,date_added,model,mileage,fuel,engine_capacity,auto_manual,price,Time_added,Cost
0,KIA Sportage 2021 AWD,Lahore,Updated less than a minute ago,2021,"35,000 km",Petrol,2000 cc,Automatic,PKR 56 lacs,13/6/2022,5600000.0
1,Toyota Prius 2020 A Premium Touring Selection,Islamabad,Updated 2 minutes ago,2020,"29,000 km",Petrol,1800 cc,Automatic,PKR 73 lacs,13/6/2022,7300000.0
2,Toyota Yaris 2022 ATIV X CVT 1.5,Karachi,Updated 2 minutes ago,2022,30 km,Petrol,0.0 kWh,Automatic,PKR 37.9 lacs,13/6/2022,3790000.0
3,Suzuki Alto 2022 VXR,Rawalpindi,Updated 5 minutes ago,2022,400 km,Petrol,660 cc,Manual,PKR 20.6 lacs,13/6/2022,2060000.0
4,Toyota Vitz 2008 F 1.0,Rawalpindi,Updated 7 minutes ago,2008,"150,000 km",Petrol,1000 cc,Automatic,PKR 17.25 lacs,13/6/2022,1725000.0
...,...,...,...,...,...,...,...,...,...,...,...
60394,Suzuki Mehran 2019 VX Euro II,Islamabad,Updated about 1 month ago,2019,"24,000 km",Petrol,800 cc,Manual,PKR 11.2 lacs,13/5/2022,1120000.0
60395,Honda BR-V 2018 i-VTEC S,Mansehra,Updated about 1 month ago,2018,"65,000 km",Petrol,1500 cc,Automatic,PKR 35.25 lacs,13/5/2022,3525000.0
60396,Suzuki Alto 2009,Islamabad,Updated about 1 month ago,2009,"224,000 km",Petrol,1000 cc,Manual,PKR 8 lacs,13/5/2022,800000.0
60397,Suzuki Wagon R 2022 VXL,Peshawar,Updated about 1 month ago,2022,10 km,Petrol,1000 cc,Manual,PKR 23 lacs,13/5/2022,2300000.0
60398,Toyota Prius 2013 S LED Edition 1.8,Faisalabad,Updated about 1 month ago,2013,"200,000 km",Hybrid,1800 cc,Automatic,PKR 31.5 lacs,13/5/2022,3150000.0

In [5]:
engine_cap=[]
for i in range(len(df.engine_capacity)):
    x=df.engine_capacity[i].lower()
    num=float(x.strip(' cc').strip(' kwh'))
    if 'kwh' in x:
        hp=num*1000/746
        cc=hp*22
        value=round(cc)
    else:
        value=x.strip(' cc')
    engine_cap.append(value)
df.insert(11,'Engine_cap_cc',engine_cap)
df

,vehicle_name,city,date_added,model,mileage,fuel,engine_capacity,auto_manual,price,Time_added,Cost,Engine_cap_cc
0,KIA Sportage 2021 AWD,Lahore,Updated less than a minute ago,2021,"35,000 km",Petrol,2000 cc,Automatic,PKR 56 lacs,13/6/2022,5600000.0,2000
1,Toyota Prius 2020 A Premium Touring Selection,Islamabad,Updated 2 minutes ago,2020,"29,000 km",Petrol,1800 cc,Automatic,PKR 73 lacs,13/6/2022,7300000.0,1800
2,Toyota Yaris 2022 ATIV X CVT 1.5,Karachi,Updated 2 minutes ago,2022,30 km,Petrol,0.0 kWh,Automatic,PKR 37.9 lacs,13/6/2022,3790000.0,0
3,Suzuki Alto 2022 VXR,Rawalpindi,Updated 5 minutes ago,2022,400 km,Petrol,660 cc,Manual,PKR 20.6 lacs,13/6/2022,2060000.0,660
4,Toyota Vitz 2008 F 1.0,Rawalpindi,Updated 7 minutes ago,2008,"150,000 km",Petrol,1000 cc,Automatic,PKR 17.25 lacs,13/6/2022,1725000.0,1000
...,...,...,...,...,...,...,...,...,...,...,...,...
60394,Suzuki Mehran 2019 VX Euro II,Islamabad,Updated about 1 month ago,2019,"24,000 km",Petrol,800 cc,Manual,PKR 11.2 lacs,13/5/2022,1120000.0,800
60395,Honda BR-V 2018 i-VTEC S,Mansehra,Updated about 1 month ago,2018,"65,000 km",Petrol,1500 cc,Automatic,PKR 35.25 lacs,13/5/2022,3525000.0,1500
60396,Suzuki Alto 2009,Islamabad,Updated about 1 month ago,2009,"224,000 km",Petrol,1000 cc,Manual,PKR 8 lacs,13/5/2022,800000.0,1000
60397,Suzuki Wagon R 2022 VXL,Peshawar,Updated about 1 month ago,2022,10 km,Petrol,1000 cc,Manual,PKR 23 lacs,13/5/2022,2300000.0,1000
60398,Toyota Prius 2013 S LED Edition 1.8,Faisalabad,Updated about 1 month ago,2013,"200,000 km",Hybrid,1800 cc,Automatic,PKR 31.5 lacs,13/5/2022,3150000.0,1800

In [6]:
df['mileage']=df['mileage'].str.replace(',','').str.replace(' km','')
df.rename(columns={'mileage':'mileage_km'},inplace=True)
df

,vehicle_name,city,date_added,model,mileage_km,fuel,engine_capacity,auto_manual,price,Time_added,Cost,Engine_cap_cc
0,KIA Sportage 2021 AWD,Lahore,Updated less than a minute ago,2021,35000,Petrol,2000 cc,Automatic,PKR 56 lacs,13/6/2022,5600000.0,2000
1,Toyota Prius 2020 A Premium Touring Selection,Islamabad,Updated 2 minutes ago,2020,29000,Petrol,1800 cc,Automatic,PKR 73 lacs,13/6/2022,7300000.0,1800
2,Toyota Yaris 2022 ATIV X CVT 1.5,Karachi,Updated 2 minutes ago,2022,30,Petrol,0.0 kWh,Automatic,PKR 37.9 lacs,13/6/2022,3790000.0,0
3,Suzuki Alto 2022 VXR,Rawalpindi,Updated 5 minutes ago,2022,400,Petrol,660 cc,Manual,PKR 20.6 lacs,13/6/2022,2060000.0,660
4,Toyota Vitz 2008 F 1.0,Rawalpindi,Updated 7 minutes ago,2008,150000,Petrol,1000 cc,Automatic,PKR 17.25 lacs,13/6/2022,1725000.0,1000
...,...,...,...,...,...,...,...,...,...,...,...,...
60394,Suzuki Mehran 2019 VX Euro II,Islamabad,Updated about 1 month ago,2019,24000,Petrol,800 cc,Manual,PKR 11.2 lacs,13/5/2022,1120000.0,800
60395,Honda BR-V 2018 i-VTEC S,Mansehra,Updated about 1 month ago,2018,65000,Petrol,1500 cc,Automatic,PKR 35.25 lacs,13/5/2022,3525000.0,1500
60396,Suzuki Alto 2009,Islamabad,Updated about 1 month ago,2009,224000,Petrol,1000 cc,Manual,PKR 8 lacs,13/5/2022,800000.0,1000
60397,Suzuki Wagon R 2022 VXL,Peshawar,Updated about 1 month ago,2022,10,Petrol,1000 cc,Manual,PKR 23 lacs,13/5/2022,2300000.0,1000
60398,Toyota Prius 2013 S LED Edition 1.8,Faisalabad,Updated about 1 month ago,2013,200000,Hybrid,1800 cc,Automatic,PKR 31.5 lacs,13/5/2022,3150000.0,1800

In [7]:
df=df.drop(columns=['date_added','engine_capacity','price'])
df

,vehicle_name,city,model,mileage_km,fuel,auto_manual,Time_added,Cost,Engine_cap_cc
0,KIA Sportage 2021 AWD,Lahore,2021,35000,Petrol,Automatic,13/6/2022,5600000.0,2000
1,Toyota Prius 2020 A Premium Touring Selection,Islamabad,2020,29000,Petrol,Automatic,13/6/2022,7300000.0,1800
2,Toyota Yaris 2022 ATIV X CVT 1.5,Karachi,2022,30,Petrol,Automatic,13/6/2022,3790000.0,0
3,Suzuki Alto 2022 VXR,Rawalpindi,2022,400,Petrol,Manual,13/6/2022,2060000.0,660
4,Toyota Vitz 2008 F 1.0,Rawalpindi,2008,150000,Petrol,Automatic,13/6/2022,1725000.0,1000
...,...,...,...,...,...,...,...,...,...
60394,Suzuki Mehran 2019 VX Euro II,Islamabad,2019,24000,Petrol,Manual,13/5/2022,1120000.0,800
60395,Honda BR-V 2018 i-VTEC S,Mansehra,2018,65000,Petrol,Automatic,13/5/2022,3525000.0,1500
60396,Suzuki Alto 2009,Islamabad,2009,224000,Petrol,Manual,13/5/2022,800000.0,1000
60397,Suzuki Wagon R 2022 VXL,Peshawar,2022,10,Petrol,Manual,13/5/2022,2300000.0,1000
60398,Toyota Prius 2013 S LED Edition 1.8,Faisalabad,2013,200000,Hybrid,Automatic,13/5/2022,3150000.0,1800

In [8]:
df.to_csv('modified_pakwheels.csv')

In [9]:
df=pd.read_excel(r'modified_pakwheels 3.xlsx')
df=df.drop(columns=['Unnamed: 0'])
df

,vehicle_name,city,model,mileage_km,fuel,auto_manual,Time_added,Cost,Engine_cap_cc,oil_price,dollar_rate,interest_rate
0,KIA Sportage 2021 AWD,Lahore,2021,35000,Petrol,Automatic,13/6/2022,5600000,2000,120.93,204.18,15.100000
1,Toyota Prius 2020 A Premium Touring Selection,Islamabad,2020,29000,Petrol,Automatic,13/6/2022,7300000,1800,120.93,204.18,15.100000
2,Toyota Yaris 2022 ATIV X CVT 1.5,Karachi,2022,30,Petrol,Automatic,13/6/2022,3790000,0,120.93,204.18,15.100000
3,Suzuki Alto 2022 VXR,Rawalpindi,2022,400,Petrol,Manual,13/6/2022,2060000,660,120.93,204.18,15.100000
4,Toyota Vitz 2008 F 1.0,Rawalpindi,2008,150000,Petrol,Automatic,13/6/2022,1725000,1000,120.93,204.18,15.100000
...,...,...,...,...,...,...,...,...,...,...,...,...
60394,Suzuki Mehran 2019 VX Euro II,Islamabad,2019,24000,Petrol,Manual,13/5/2022,1120000,800,110.49,192.95,14.423333
60395,Honda BR-V 2018 i-VTEC S,Mansehra,2018,65000,Petrol,Automatic,13/5/2022,3525000,1500,110.49,192.95,14.423333
60396,Suzuki Alto 2009,Islamabad,2009,224000,Petrol,Manual,13/5/2022,800000,1000,110.49,192.95,14.423333
60397,Suzuki Wagon R 2022 VXL,Peshawar,2022,10,Petrol,Manual,13/5/2022,2300000,1000,110.49,192.95,14.423333
60398,Toyota Prius 2013 S LED Edition 1.8,Faisalabad,2013,200000,Hybrid,Automatic,13/5/2022,3150000,1800,110.49,192.95,14.423333

In [10]:
for i in range(len(df.Cost)):
    x=df.Cost[i]
    if x=='Call':
        df.drop(i,inplace=True)

In [11]:
df=df.reset_index(drop=True)
df

,vehicle_name,city,model,mileage_km,fuel,auto_manual,Time_added,Cost,Engine_cap_cc,oil_price,dollar_rate,interest_rate
0,KIA Sportage 2021 AWD,Lahore,2021,35000,Petrol,Automatic,13/6/2022,5600000,2000,120.93,204.18,15.100000
1,Toyota Prius 2020 A Premium Touring Selection,Islamabad,2020,29000,Petrol,Automatic,13/6/2022,7300000,1800,120.93,204.18,15.100000
2,Toyota Yaris 2022 ATIV X CVT 1.5,Karachi,2022,30,Petrol,Automatic,13/6/2022,3790000,0,120.93,204.18,15.100000
3,Suzuki Alto 2022 VXR,Rawalpindi,2022,400,Petrol,Manual,13/6/2022,2060000,660,120.93,204.18,15.100000
4,Toyota Vitz 2008 F 1.0,Rawalpindi,2008,150000,Petrol,Automatic,13/6/2022,1725000,1000,120.93,204.18,15.100000
...,...,...,...,...,...,...,...,...,...,...,...,...
59096,Suzuki Mehran 2019 VX Euro II,Islamabad,2019,24000,Petrol,Manual,13/5/2022,1120000,800,110.49,192.95,14.423333
59097,Honda BR-V 2018 i-VTEC S,Mansehra,2018,65000,Petrol,Automatic,13/5/2022,3525000,1500,110.49,192.95,14.423333
59098,Suzuki Alto 2009,Islamabad,2009,224000,Petrol,Manual,13/5/2022,800000,1000,110.49,192.95,14.423333
59099,Suzuki Wagon R 2022 VXL,Peshawar,2022,10,Petrol,Manual,13/5/2022,2300000,1000,110.49,192.95,14.423333
59100,Toyota Prius 2013 S LED Edition 1.8,Faisalabad,2013,200000,Hybrid,Automatic,13/5/2022,3150000,1800,110.49,192.95,14.423333

In [12]:
UQ=df['Engine_cap_cc'].quantile(0.75)
LQ=df['Engine_cap_cc'].quantile(0.25)
IQR=UQ-LQ
UQ_new=UQ+IQR*1.5
LQ_new=LQ-IQR*1.5
print(UQ_new,LQ_new)
#df=df.loc[df['Engine_cap_cc']<UQ_new]
df=df.loc[df['Engine_cap_cc']>LQ_new]
df = df.reset_index(drop = True)

UQ=df['Cost'].quantile(0.75)
LQ=df['Cost'].quantile(0.25)
IQR=UQ-LQ
UQ_new=UQ+IQR*1.5
LQ_new=LQ-IQR*1.5
print(UQ_new,LQ_new)
#df=df.loc[df['Engine_cap_cc']<UQ_new]
df=df.loc[df['Cost']>50000]
df = df.reset_index(drop = True)
df

2500.0 100.0
6322500.0 -2137500.0

,vehicle_name,city,model,mileage_km,fuel,auto_manual,Time_added,Cost,Engine_cap_cc,oil_price,dollar_rate,interest_rate
0,KIA Sportage 2021 AWD,Lahore,2021,35000,Petrol,Automatic,13/6/2022,5600000,2000,120.93,204.18,15.100000
1,Toyota Prius 2020 A Premium Touring Selection,Islamabad,2020,29000,Petrol,Automatic,13/6/2022,7300000,1800,120.93,204.18,15.100000
2,Suzuki Alto 2022 VXR,Rawalpindi,2022,400,Petrol,Manual,13/6/2022,2060000,660,120.93,204.18,15.100000
3,Toyota Vitz 2008 F 1.0,Rawalpindi,2008,150000,Petrol,Automatic,13/6/2022,1725000,1000,120.93,204.18,15.100000
4,Nissan Dayz 2019 X,Karachi,2019,42000,Petrol,Automatic,13/6/2022,2650000,660,120.93,204.18,15.100000
...,...,...,...,...,...,...,...,...,...,...,...,...
57110,Suzuki Mehran 2019 VX Euro II,Islamabad,2019,24000,Petrol,Manual,13/5/2022,1120000,800,110.49,192.95,14.423333
57111,Honda BR-V 2018 i-VTEC S,Mansehra,2018,65000,Petrol,Automatic,13/5/2022,3525000,1500,110.49,192.95,14.423333
57112,Suzuki Alto 2009,Islamabad,2009,224000,Petrol,Manual,13/5/2022,800000,1000,110.49,192.95,14.423333
57113,Suzuki Wagon R 2022 VXL,Peshawar,2022,10,Petrol,Manual,13/5/2022,2300000,1000,110.49,192.95,14.423333
57114,Toyota Prius 2013 S LED Edition 1.8,Faisalabad,2013,200000,Hybrid,Automatic,13/5/2022,3150000,1800,110.49,192.95,14.423333

In [15]:
df['vehicle_name'].unique()

array(['KIA Sportage  2021 AWD',
       'Toyota Prius  2020 A Premium Touring Selection',
       'Suzuki Alto  2022 VXR', ..., 'Mitsubishi Pajero Mini  1987 VR',
       'Mitsubishi L200  1996 2.5 D/C', 'Audi Q8  2006 '], dtype=object)

In [13]:
vehicle_name_mod=[]
for i in range(len(df.vehicle_name)):
    car=df.vehicle_name[i]
    for i in car.split('  '):
        vehicle_name_mod.append(i)
        break
df.insert(12,'Vehicle_name_mod',vehicle_name_mod)
df

,vehicle_name,city,model,mileage_km,fuel,auto_manual,Time_added,Cost,Engine_cap_cc,oil_price,dollar_rate,interest_rate,Vehicle_name_mod
0,KIA Sportage 2021 AWD,Lahore,2021,35000,Petrol,Automatic,13/6/2022,5600000,2000,120.93,204.18,15.100000,KIA Sportage
1,Toyota Prius 2020 A Premium Touring Selection,Islamabad,2020,29000,Petrol,Automatic,13/6/2022,7300000,1800,120.93,204.18,15.100000,Toyota Prius
2,Suzuki Alto 2022 VXR,Rawalpindi,2022,400,Petrol,Manual,13/6/2022,2060000,660,120.93,204.18,15.100000,Suzuki Alto
3,Toyota Vitz 2008 F 1.0,Rawalpindi,2008,150000,Petrol,Automatic,13/6/2022,1725000,1000,120.93,204.18,15.100000,Toyota Vitz
4,Nissan Dayz 2019 X,Karachi,2019,42000,Petrol,Automatic,13/6/2022,2650000,660,120.93,204.18,15.100000,Nissan Dayz
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57110,Suzuki Mehran 2019 VX Euro II,Islamabad,2019,24000,Petrol,Manual,13/5/2022,1120000,800,110.49,192.95,14.423333,Suzuki Mehran
57111,Honda BR-V 2018 i-VTEC S,Mansehra,2018,65000,Petrol,Automatic,13/5/2022,3525000,1500,110.49,192.95,14.423333,Honda BR-V
57112,Suzuki Alto 2009,Islamabad,2009,224000,Petrol,Manual,13/5/2022,800000,1000,110.49,192.95,14.423333,Suzuki Alto
57113,Suzuki Wagon R 2022 VXL,Peshawar,2022,10,Petrol,Manual,13/5/2022,2300000,1000,110.49,192.95,14.423333,Suzuki Wagon R
57114,Toyota Prius 2013 S LED Edition 1.8,Faisalabad,2013,200000,Hybrid,Automatic,13/5/2022,3150000,1800,110.49,192.95,14.423333,Toyota Prius

In [17]:
df['Vehicle_name_mod'].value_counts()

Toyota Corolla              8260
Suzuki Mehran               3830
Suzuki Cultus               3488
Honda City                  3438
Honda Civic                 3367
                            ...
Subaru Forester                1
Nissan Latio                   1
Audi A6                        1
Honda Civic Reborn 2011        1
Audi Q8                        1
Name: Vehicle_name_mod, Length: 1042, dtype: int64

In [14]:
cars_data=['Corolla','Civic','Mehran','Cultus','City','Alto','Vitz','Wagon R','Bolan','Prado','Swift','Hilux','Land Cruiser','Cuore','Passo','Sportage','Vezel','Fortuner','Khyber','Mira','Yaris','HS','Santro','Baleno','Picanto','Every','Aqua','Karvaan','Prius','BR-V']

In [15]:
final=[]
for i in range(len(df.Vehicle_name_mod)):
    x=False
    car=df.Vehicle_name_mod[i]
    for j in cars_data:
        if j in car:
            x=True
            final.append(j)
    if x==False:
        final.append('others')
df.insert(13,'Vehicle',final)
df

,vehicle_name,city,model,mileage_km,fuel,auto_manual,Time_added,Cost,Engine_cap_cc,oil_price,dollar_rate,interest_rate,Vehicle_name_mod,Vehicle
0,KIA Sportage 2021 AWD,Lahore,2021,35000,Petrol,Automatic,13/6/2022,5600000,2000,120.93,204.18,15.100000,KIA Sportage,Sportage
1,Toyota Prius 2020 A Premium Touring Selection,Islamabad,2020,29000,Petrol,Automatic,13/6/2022,7300000,1800,120.93,204.18,15.100000,Toyota Prius,Prius
2,Suzuki Alto 2022 VXR,Rawalpindi,2022,400,Petrol,Manual,13/6/2022,2060000,660,120.93,204.18,15.100000,Suzuki Alto,Alto
3,Toyota Vitz 2008 F 1.0,Rawalpindi,2008,150000,Petrol,Automatic,13/6/2022,1725000,1000,120.93,204.18,15.100000,Toyota Vitz,Vitz
4,Nissan Dayz 2019 X,Karachi,2019,42000,Petrol,Automatic,13/6/2022,2650000,660,120.93,204.18,15.100000,Nissan Dayz,others
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57110,Suzuki Mehran 2019 VX Euro II,Islamabad,2019,24000,Petrol,Manual,13/5/2022,1120000,800,110.49,192.95,14.423333,Suzuki Mehran,Mehran
57111,Honda BR-V 2018 i-VTEC S,Mansehra,2018,65000,Petrol,Automatic,13/5/2022,3525000,1500,110.49,192.95,14.423333,Honda BR-V,BR-V
57112,Suzuki Alto 2009,Islamabad,2009,224000,Petrol,Manual,13/5/2022,800000,1000,110.49,192.95,14.423333,Suzuki Alto,Alto
57113,Suzuki Wagon R 2022 VXL,Peshawar,2022,10,Petrol,Manual,13/5/2022,2300000,1000,110.49,192.95,14.423333,Suzuki Wagon R,Wagon R
57114,Toyota Prius 2013 S LED Edition 1.8,Faisalabad,2013,200000,Hybrid,Automatic,13/5/2022,3150000,1800,110.49,192.95,14.423333,Toyota Prius,Prius

In [20]:
df['Vehicle'].nunique()

31

In [16]:
df=df.drop(columns=['city','vehicle_name','Vehicle_name_mod','Time_added'])
df

,model,mileage_km,fuel,auto_manual,Cost,Engine_cap_cc,oil_price,dollar_rate,interest_rate,Vehicle
0,2021,35000,Petrol,Automatic,5600000,2000,120.93,204.18,15.100000,Sportage
1,2020,29000,Petrol,Automatic,7300000,1800,120.93,204.18,15.100000,Prius
2,2022,400,Petrol,Manual,2060000,660,120.93,204.18,15.100000,Alto
3,2008,150000,Petrol,Automatic,1725000,1000,120.93,204.18,15.100000,Vitz
4,2019,42000,Petrol,Automatic,2650000,660,120.93,204.18,15.100000,others
...,...,...,...,...,...,...,...,...,...,...
57110,2019,24000,Petrol,Manual,1120000,800,110.49,192.95,14.423333,Mehran
57111,2018,65000,Petrol,Automatic,3525000,1500,110.49,192.95,14.423333,BR-V
57112,2009,224000,Petrol,Manual,800000,1000,110.49,192.95,14.423333,Alto
57113,2022,10,Petrol,Manual,2300000,1000,110.49,192.95,14.423333,Wagon R
57114,2013,200000,Hybrid,Automatic,3150000,1800,110.49,192.95,14.423333,Prius

In [17]:
#one hot encoding
df2=pd.get_dummies(df,columns=['fuel','auto_manual','Vehicle'])
df2

,model,mileage_km,Cost,Engine_cap_cc,oil_price,dollar_rate,interest_rate,fuel_CNG,fuel_Diesel,fuel_Electric,...,Vehicle_Prado,Vehicle_Prius,Vehicle_Santro,Vehicle_Sportage,Vehicle_Swift,Vehicle_Vezel,Vehicle_Vitz,Vehicle_Wagon R,Vehicle_Yaris,Vehicle_others
0,2021,35000,5600000,2000,120.93,204.18,15.100000,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,2020,29000,7300000,1800,120.93,204.18,15.100000,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,2022,400,2060000,660,120.93,204.18,15.100000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2008,150000,1725000,1000,120.93,204.18,15.100000,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,2019,42000,2650000,660,120.93,204.18,15.100000,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57110,2019,24000,1120000,800,110.49,192.95,14.423333,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57111,2018,65000,3525000,1500,110.49,192.95,14.423333,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57112,2009,224000,800000,1000,110.49,192.95,14.423333,0,0,0,...,0,0,0,0,0,0,0,0,0,0
57113,2022,10,2300000,1000,110.49,192.95,14.423333,0,0,0,...,0,0,0,0,0,0,0,1,0,0
57114,2013,200000,3150000,1800,110.49,192.95,14.423333,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [29]:
df2.columns

Index(['model', 'mileage_km', 'Cost', 'Engine_cap_cc', 'oil_price',
       'dollar_rate', 'interest_rate', 'fuel_CNG', 'fuel_Diesel',
       'fuel_Electric', 'fuel_Hybrid', 'fuel_LPG', 'fuel_Petrol',
       'auto_manual_Automatic', 'auto_manual_Manual', 'Vehicle_Alto',
       'Vehicle_Aqua', 'Vehicle_BR-V', 'Vehicle_Baleno', 'Vehicle_Bolan',
       'Vehicle_City', 'Vehicle_Civic', 'Vehicle_Corolla', 'Vehicle_Cultus',
       'Vehicle_Cuore', 'Vehicle_Every', 'Vehicle_Fortuner', 'Vehicle_HS',
       'Vehicle_Hilux', 'Vehicle_Karvaan', 'Vehicle_Khyber',
       'Vehicle_Land Cruiser', 'Vehicle_Mehran', 'Vehicle_Mira',
       'Vehicle_Passo', 'Vehicle_Picanto', 'Vehicle_Prado', 'Vehicle_Prius',
       'Vehicle_Santro', 'Vehicle_Sportage', 'Vehicle_Swift', 'Vehicle_Vezel',
       'Vehicle_Vitz', 'Vehicle_Wagon R', 'Vehicle_Yaris', 'Vehicle_others'],
      dtype='object')

In [23]:
corr_matrix = df2.corr().abs()
corr_df=pd.DataFrame(corr_matrix)
corr_df

,model,mileage_km,Engine_cap_cc,oil_price,dollar_rate,interest_rate,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_Hybrid,...,Vehicle_Prado,Vehicle_Prius,Vehicle_Santro,Vehicle_Sportage,Vehicle_Swift,Vehicle_Vezel,Vehicle_Vitz,Vehicle_Wagon R,Vehicle_Yaris,Vehicle_others
model,1.000000,0.376288,0.081903,0.079147,0.057714,0.011525,0.136130,0.150793,0.034236,0.093497,...,0.072775,0.012128,0.058376,0.093362,0.074614,0.058116,0.014478,0.124761,0.099700,0.143457
mileage_km,0.376288,1.000000,0.035968,0.039109,0.019852,0.001178,0.027885,0.050816,0.028489,0.026483,...,0.032302,0.031472,0.050293,0.068385,0.025495,0.020863,0.002500,0.056722,0.074472,0.006276
Engine_cap_cc,0.081903,0.035968,1.000000,0.024252,0.014945,0.009675,0.040160,0.364744,0.140037,0.021415,...,0.266787,0.029912,0.043166,0.068569,0.027330,0.007942,0.086061,0.096566,0.009010,0.114504
oil_price,0.079147,0.039109,0.024252,1.000000,0.455508,0.312778,0.011399,0.014642,0.007603,0.007388,...,0.014106,0.006411,0.007799,0.013946,0.002564,0.002678,0.016404,0.014136,0.001969,0.000220
dollar_rate,0.057714,0.019852,0.014945,0.455508,1.000000,0.204006,0.019621,0.009449,0.004726,0.012866,...,0.008149,0.003174,0.005401,0.002927,0.007839,0.000426,0.009289,0.011309,0.000210,0.003781
interest_rate,0.011525,0.001178,0.009675,0.312778,0.204006,1.000000,0.000401,0.007611,0.002066,0.003738,...,0.001295,0.001964,0.003168,0.005512,0.003540,0.005078,0.005570,0.007754,0.002605,0.010256
fuel_CNG,0.136130,0.027885,0.040160,0.011399,0.019621,0.000401,1.000000,0.021368,0.003009,0.016157,...,0.013175,0.007465,0.011115,0.005786,0.011000,0.009995,0.016231,0.014920,0.008748,0.014155
fuel_Diesel,0.150793,0.050816,0.364744,0.014642,0.009449,0.007611,0.021368,1.000000,0.006970,0.037431,...,0.138152,0.017294,0.019150,0.001910,0.028828,0.023156,0.037602,0.034021,0.020267,0.035369
fuel_Electric,0.034236,0.028489,0.140037,0.007603,0.004726,0.002066,0.003009,0.006970,1.000000,0.005270,...,0.004298,0.002435,0.002696,0.003109,0.004059,0.003260,0.005294,0.004867,0.002854,0.059811
fuel_Hybrid,0.093497,0.026483,0.021415,0.007388,0.012866,0.003738,0.016157,0.037431,0.005270,1.000000,...,0.023079,0.148985,0.014480,0.016695,0.021798,0.241311,0.016708,0.017604,0.007032,0.084510
fuel_LPG,0.028234,0.000078,0.000705,0.006361,0.004930,0.000452,0.001449,0.003357,0.000473,0.002538,...,0.002070,0.001173,0.001299,0.001497,0.001955,0.001570,0.002550,0.002344,0.001374,0.014688
fuel_Petrol,0.103895,0.029400,0.291821,0.009487,0.005532,0.007907,0.315026,0.729807,0.102760,0.551828,...,0.086372,0.071355,0.019628,0.013647,0.039008,0.120074,0.044647,0.021294,0.022906,0.088782
auto_manual_Automatic,0.301518,0.137230,0.314054,0.081426,0.059969,0.008237,0.088603,0.033481,0.029878,0.161746,...,0.120388,0.076907,0.084530,0.083935,0.046859,0.102973,0.163805,0.090530,0.033144,0.179914
auto_manual_Manual,0.301518,0.137230,0.314054,0.081426,0.059969,0.008237,0.088603,0.033481,0.029878,0.161746,...,0.120388,0.076907,0.084530,0.083935,0.046859,0.102973,0.163805,0.090530,0.033144,0.179914
Vehicle_Alto,0.065052,0.042199,0.171051,0.009558,0.012837,0.005567,0.019512,0.049426,0.006959,0.035856,...,0.030475,0.017267,0.019120,0.022045,0.028783,0.023119,0.037543,0.034512,0.020235,0.116356
Vehicle_Aqua,0.047064,0.005212,0.005853,0.015724,0.016370,0.002175,0.007498,0.017370,0.002446,0.440611,...,0.010710,0.006068,0.006719,0.007748,0.010115,0.008125,0.013194,0.012129,0.007111,0.040892
Vehicle_BR-V,0.065224,0.036049,0.005779,0.002614,0.003691,0.003866,0.007220,0.016727,0.002355,0.012648,...,0.010313,0.005844,0.006471,0.007461,0.009741,0.007824,0.012706,0.011680,0.006848,0.039378
Vehicle_Baleno,0.071153,0.055147,0.013706,0.009999,0.010601,0.003031,0.005066,0.018779,0.002644,0.014199,...,0.011579,0.006561,0.007265,0.008376,0.010936,0.008784,0.014264,0.013112,0.007688,0.044209
Vehicle_Bolan,0.000040,0.018987,0.103355,0.028893,0.009006,0.005450,0.031672,0.030655,0.004316,0.022387,...,0.018901,0.010709,0.011859,0.013673,0.017852,0.014339,0.023285,0.021405,0.012550,0.072166
Vehicle_City,0.059451,0.010316,0.028931,0.017324,0.000283,0.007479,0.019665,0.056309,0.007928,0.042577,...,0.034718,0.019672,0.021783,0.025115,0.032791,0.026339,0.042771,0.039317,0.023053,0.132559
Vehicle_Civic,0.035406,0.069572,0.106980,0.010206,0.009287,0.007879,0.019384,0.076717,0.010802,0.049326,...,0.047302,0.026801,0.029678,0.034218,0.044676,0.035885,0.058273,0.053568,0.031408,0.180604
Vehicle_Corolla,0.013552,0.103028,0.019306,0.009309,0.009529,0.001591,0.012815,0.034081,0.014006,0.051947,...,0.061330,0.034750,0.038479,0.044366,0.057925,0.046528,0.075555,0.069454,0.040723,0.234166
Vehicle_Cultus,0.005331,0.036456,0.139576,0.016883,0.009383,0.002361,0.007008,0.056743,0.007990,0.042011,...,0.034986,0.019823,0.021951,0.025309,0.033044,0.026542,0.043101,0.039621,0.023231,0.133582
Vehicle_Cuore,0.050474,0.032983,0.086965,0.010170,0.010445,0.000520,0.017785,0.024748,0.003485,0.017739,...,0.015259,0.008646,0.009574,0.011038,0.014412,0.011576,0.018798,0.017280,0.010132,0.058260
Vehicle_Every,0.029505,0.007453,0.084940,0.006460,0.001687,0.001313,0.008729,0.020223,0.002848,0.015291,...,0.012469,0.007065,0.007823,0.009020,0.011777,0.009460,0.015361,0.014121,0.008279,0.047609
Vehicle_Fortuner,0.089995,0.059552,0.160675,0.009154,0.000345,0.002983,0.009479,0.163926,0.003092,0.016604,...,0.013540,0.007672,0.008495,0.009795,0.012788,0.010272,0.016680,0.015333,0.008990,0.051696
Vehicle_HS,0.106667,0.083235,0.006981,0.000030,0.005947,0.007156,0.008888,0.020590,0.002899,0.005072,...,0.012695,0.007193,0.007965,0.009184,0.011991,0.009631,0.015640,0.014377,0.008430,0.048473
Vehicle_Hilux,0.047237,0.018088,0.216047,0.006093,0.009721,0.001029,0.012118,0.543814,0.003953,0.021226,...,0.017309,0.009807,0.010860,0.012521,0.016348,0.013131,0.021323,0.019602,0.011493,0.066087
Vehicle_Karvaan,0.087864,0.063869,0.041640,0.001382,0.007496,0.004723,0.007299,0.016909,0.002381,0.012786,...,0.010426,0.005907,0.006541,0.007542,0.009847,0.007910,0.012844,0.011807,0.006923,0.039807
Vehicle_Khyber,0.181675,0.025173,0.049692,0.010430,0.015938,0.001721,0.091177,0.022160,0.003120,0.015670,...,0.013663,0.007742,0.008572,0.009884,0.012905,0.010365,0.016832,0.015473,0.009072,0.052168
Vehicle_Land Cruiser,0.101835,0.019184,0.411230,0.009034,0.005170,0.010344,0.011490,0.157529,0.003748,0.020128,...,0.016413,0.009299,0.010297,0.011873,0.015502,0.012451,0.020219,0.018587,0.010898,0.062666
Vehicle_Mehran,0.047287,0.015807,0.215029,0.030748,0.018615,0.002232,0.031627,0.059650,0.008399,0.044248,...,0.036779,0.020839,0.023075,0.026606,0.034737,0.027902,0.045309,0.041651,0.024421,0.140426
Vehicle_Mira,0.040594,0.022683,0.091110,0.010838,0.015160,0.000377,0.009161,0.021223,0.002988,0.014915,...,0.013086,0.007414,0.008210,0.009466,0.012359,0.009927,0.016121,0.014819,0.008689,0.049963
Vehicle_Passo,0.033994,0.011123,0.053965,0.003670,0.001915,0.000339,0.009946,0.023041,0.003244,0.016377,...,0.014206,0.008049,0.008913,0.010277,0.013418,0.010777,0.017501,0.016088,0.009433,0.054241
Vehicle_Picanto,0.097610,0.074338,0.047014,0.001373,0.006680,0.002641,0.008207,0.019012,0.002677,0.014375,...,0.011722,0.006642,0.007355,0.008480,0.011071,0.008893,0.014441,0.013275,0.007783,0.044756
Vehicle_Prado,0.072775,0.032302,0.266787,0.014106,0.008149,0.001295,0.013175,0.138152,0.004298,0.023079,...,1.000000,0.010663,0.011807,0.013614,0.017774,0.014277,0.023184,0.021312,0.012496,0.071854
Vehicle_Prius,0.012128,0.031472,0.029912,0.006411,0.003174,0.001964,0.007465,0.017294,0.002435,0.148985,...,0.010663,1.000000,0.006690,0.007714,0.010071,0.008089,0.013136,0.012076,0.007080,0.040713
Vehicle_Santro,0.058376,0.050293,0.043166,0.007799,0.005401,0.003168,0.011115,0.019150,0.002696,0.014480,...,0.011807,0.006690,1.000000,0.008541,0.011152,0.008958,0.014546,0.013371,0.007840,0.045082
Vehicle_Sportage,0.093362,0.068385,0.068569,0.013946,0.002927,0.005512,0.005786,0.001910,0.003109,0.016695,...,0.013614,0.007714,0.008541,1.000000,0.012858,0.010328,0.016772,0.015417,0.009040,0.051979
Vehicle_Swift,0.074614,0.025495,0.027330,0.002564,0.007839,0.003540,0.011000,0.028828,0.004059,0.021798,...,0.017774,0.010071,0.011152,0.012858,1.000000,0.013485,0.021897,0.020129,0.011802,0.067865
Vehicle_Vezel,0.058116,0.020863,0.007942,0.002678,0.000426,0.005078,0.009995,0.023156,0.003260,0.241311,...,0.014277,0.008089,0.008958,0.010328,0.013485,1.000000,0.017589,0.016168,0.009480,0.054512
Vehicle_Vitz,0.014478,0.002500,0.086061,0.016404,0.009289,0.005570,0.016231,0.037602,0.005294,0.016708,...,0.023184,0.013136,0.014546,0.016772,0.021897,0.017589,1.000000,0.026255,0.015394,0.088520
Vehicle_Wagon R,0.124761,0.056722,0.096566,0.014136,0.011309,0.007754,0.014920,0.034021,0.004867,0.017604,...,0.021312,0.012076,0.013371,0.015417,0.020129,0.016168,0.026255,1.000000,0.014151,0.081372
Vehicle_Yaris,0.099700,0.074472,0.009010,0.001969,0.000210,0.002605,0.008748,0.020267,0.002854,0.007032,...,0.012496,0.007080,0.007840,0.009040,0.011802,0.009480,0.015394,0.014151,1.000000,0.047711
Vehicle_others,0.143457,0.006276,0.114504,0.000220,0.003781,0.010256,0.014155,0.035369,0.059811,0.084510,...,0.071854,0.040713,0.045082,0.051979,0.067865,0.054512,0.088520,0.081372,0.047711,1.000000

In [18]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import mean_squared_error 
from math import sqrt

In [19]:
y=df2.Cost
x=df2.drop(['Cost'],axis=1)
x1_train,x1_test,y1_train,y1_test=train_test_split(x,y,test_size=0.3, random_state=np.random)
x1_train_scaled=scaler.fit_transform(x1_train)
x1_test_scaled=scaler.transform(x1_test)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error 
from math import sqrt
model=LinearRegression().fit(x1_train_scaled,y1_train)
y_pred=model.predict(x1_test_scaled)
r_sq=model.score(x1_test_scaled,y1_test)
r2_sq=model.score(x1_train_scaled,y1_train)
error = sqrt(mean_squared_error(y1_test,y_pred))
print('RMSE =', error)
print('training data:',r2_sq*100)
print('test data:',r_sq*100)

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn import metrics
for i in range(1,10,2):
    knn = KNeighborsRegressor(n_neighbors=i)
    knn.fit(x1_train_scaled, y1_train)
    y_pred=knn.predict(x1_test_scaled)
    error = sqrt(mean_squared_error(y1_test,y_pred))
    print('Test data score for k= :',i,'is', r2_score(y1_test, y_pred)*100)
    print('RMSE =', error)

In [ ]:
from sklearn.linear_model import Ridge, Lasso
from sklearn.metrics import mean_squared_error,r2_score

lasso_model = Lasso().fit(x1_train_scaled,y1_train)
y_pred=lasso_model.predict(x1_test_scaled)
error = sqrt(mean_squared_error(y1_test,y_pred))
print('Traning data score: ',lasso_model.score(x1_train_scaled,y1_train)*100)
print('Test data score: ',lasso_model.score(x1_test_scaled,y1_test)*100)
print('RMSE =', error)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
for i in range(2,20,2):
    model = RandomForestRegressor(n_estimators = i, random_state = 0)
    model.fit(x1_train_scaled,y1_train)
    y_pred=model.predict(x1_test_scaled)
    error = sqrt(mean_squared_error(y1_test,y_pred))
    print('Traning data score for',i,'decision trees:',model.score(x1_train_scaled,y1_train)*100)
    print('Test data score for',i,'decision trees:',model.score(x1_test_scaled,y1_test)*100)
    print('RMSE =', error)

In [23]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators = 18, random_state = 0)
model.fit(x1_train_scaled,y1_train)
y_pred=model.predict(x1_test_scaled)
print(model.score(x1_train_scaled,y1_train)*100)
print(model.score(x1_test_scaled,y1_test)*100)

98.20546408947158
85.5344658924299

In [21]:
import joblib

# save the model to disk

filename = 'pakwheel_model.sav'

joblib.dump(model, filename)

 

# some time later...

 

# load the model from disk

# loaded_model = joblib.load(filename)

# result = loaded_model.score(X_test, Y_test)

# print(result)

['pakwheel_model.sav']

In [66]:
print(df.iloc[430])

vehicle_name       Toyota Crown  1985 Super Select
city                                     Islamabad
date_added               Updated about 9 hours ago
model                                         1985
mileage                                 120,000 km
fuel                                        Petrol
engine_capacity                            2800 cc
auto_manual                                 Manual
price                                   PKR 10,000
Time_added                               13/6/2022
Cost                                       10000.0
Name: 430, dtype: object

In [10]:
import datetime as dt
lst=[]
x=dt.datetime(2022,6,13).date()
lst.append(x)
print(lst)

[datetime.date(2022, 6, 13)]

In [16]:

date='{}/{}/{}'.format(day,month,year)
print(date)

13/6/2022